
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/store/providers";
import MyApp from "./app";
import "./css/globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import customTheme from "@/utils/theme/custom-theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MaterialM - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Flowbite theme={{ theme: customTheme }}>
      <html lang="en" data-color-theme="Blue_Theme" >
        <head>
          <ThemeModeScript />
        </head>
        <body className={`${inter.className} DEFAULT_THEME`}>
          <Providers>
            <MyApp>{children}</MyApp>
          </Providers>
        </body>
      </html>
    </Flowbite>
  );
}
